//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueSpectator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeagueSpectator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute cannot be null or empty..
        /// </summary>
        internal static string ErrorAttribute {
            get {
                return ResourceManager.GetString("ErrorAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either the specified summoner is not currently playing a match or the API request failed..
        /// </summary>
        internal static string ErrorGameInfo {
            get {
                return ResourceManager.GetString("ErrorGameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string is empty..
        /// </summary>
        internal static string ErrorStringEmpty {
            get {
                return ResourceManager.GetString("ErrorStringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No string split separators have been provided..
        /// </summary>
        internal static string ErrorStringSeparators {
            get {
                return ResourceManager.GetString("ErrorStringSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either the specified summoner name could not be found or the API request failed..
        /// </summary>
        internal static string ErrorSummonerName {
            get {
                return ResourceManager.GetString("ErrorSummonerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception has occurred and the application must be terminated..
        /// </summary>
        internal static string ErrorUnhandledException {
            get {
                return ResourceManager.GetString("ErrorUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Client|League of Legends.exe.
        /// </summary>
        internal static string FilterGameClient {
            get {
                return ResourceManager.GetString("FilterGameClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key:.
        /// </summary>
        internal static string TextAPIKey {
            get {
                return ResourceManager.GetString("TextAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Version:.
        /// </summary>
        internal static string TextAPIVersion {
            get {
                return ResourceManager.GetString("TextAPIVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string TextCopy {
            get {
                return ResourceManager.GetString("TextCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string TextDetails {
            get {
                return ResourceManager.GetString("TextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Path:.
        /// </summary>
        internal static string TextGameClient {
            get {
                return ResourceManager.GetString("TextGameClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region:.
        /// </summary>
        internal static string TextGameRegion {
            get {
                return ResourceManager.GetString("TextGameRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string TextHide {
            get {
                return ResourceManager.GetString("TextHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        internal static string TextProceed {
            get {
                return ResourceManager.GetString("TextProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string TextSelect {
            get {
                return ResourceManager.GetString("TextSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectate.
        /// </summary>
        internal static string TextSpectate {
            get {
                return ResourceManager.GetString("TextSpectate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summoner Name:.
        /// </summary>
        internal static string TextSummonerName {
            get {
                return ResourceManager.GetString("TextSummonerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League Spectator.
        /// </summary>
        internal static string TextTitle {
            get {
                return ResourceManager.GetString("TextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        internal static string TextUnhandledException {
            get {
                return ResourceManager.GetString("TextUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown exception has occurred and the application must be terminated..
        /// </summary>
        internal static string TextUnknownException {
            get {
                return ResourceManager.GetString("TextUnknownException", resourceCulture);
            }
        }
    }
}
